### ISSUE TITLE
Problème lors de la mise à jours

### ISSUE THREAD

**Issue by Noak17** [Guilouz/BTT-TFT43-Sidewinder-X1#1]
Bonjour, j'ai un soucis lors de la mise à jour, plusieurs message d'erreur "invalid keyword" même sans fichier language

**Comment by Noak17** [comment]
![IMG_20210917_185242](https://user-images.githubusercontent.com/90931377/133851975-aa0451af-03db-4267-b378-54d7553bbcd1.jpg)

**Comment by Guilouz** [comment]
Tu n’as pas le bon fichier de configuration, utilise celui fourni dans le zip.

**Comment by Noak17** [comment]
tu parle bien du fichier config.ini dans le dossier "Copy to SD Card root directory to utdate"?

**Comment by Noak17** [comment]
![image](https://user-images.githubusercontent.com/90931377/133882363-deb2d4df-a7e7-4965-a3d9-44f6e77c7f12.png)
voici se qu'il y a a la racine de ma carte SD, j'ai suivis le tuto et pris tout les fichier dans le zip :( sauf le dossier TFT qui est plus bas dans le tuto en fonction du thème souhaité)

**Comment by Guilouz** [comment]
Oui c’est bien ça. Je suis actuellement en vacances à l’étranger, je ne peux pas vérifier ça actuellement.

**Comment by Noak17** [comment]
pas de soucis, bonne vacances

**Comment by Guilouz** [comment]
@Noak17 Essayes la dernière mise à jour.

**Comment by Noak17** [comment]
@Guilouz merci, je te tiens au courant

**Comment by Noak17** [comment]
parfait merci beaucoup
