### ISSUE TITLE
[BUG] (short description)Compilation error vith VSC

### ISSUE THREAD

**Issue by bricolo07** [Guilouz/BTT-TFT43-Sidewinder-X1#3]
### Description

Error report

Compiling .pio\build\BIGTREE_TFT43_V3_0\src\src\Libraries\Startup\stm32f2xx\startup_stm32f2xx.o
Compiling .pio\build\BIGTREE_TFT43_V3_0\src\src\Libraries\fwlib\stm32f2xx\src\stm32f2xx_adc.o
arm-none-eabi-as: unrecognized option `-x'
Compiling .pio\build\BIGTREE_TFT43_V3_0\src\src\Libraries\fwlib\stm32f2xx\src\stm32f2xx_can.o
*** [.pio\build\BIGTREE_TFT43_V3_0\src\src\Libraries\Startup\stm32f2xx\startup_stm32f2xx.o] Error 1

I can't find any explanation

**Comment by Guilouz** [comment]
Support ended for this. It's no longer supported.
